### PR TITLE
Experiment with pure memoization for the Schema

### PR DESCRIPTION
**Pull request by Soreine**
From a comment on the original PR

> @Soreine
> Memoizing has some overhead. And we opted to compare with the previous document during normalization, for performance. We assume that the state at the beginning of every transform is already normalized. From this assumption, we avoid calling the validation on nodes that have not changed. We could make a branch where we go for the pure memoization path instead, and compare the result. I can volunteer if you think this would be better.

> @ianstormtaylor
> I'd be interested in what the pure memoization path yields in terms of performance. How much work would that take do you think to benchmark?
> 
> It sounds like the "previous document" approach currently works, but it makes some assumptions that add complexity. For example, if you were to try to normalize with your own custom schema, there's not guarantee that the previous document adhered to it when you do, so that seems like it might cause issues? My guess is there are other similar problems that might crop up. Ideally we could be fully stateless in that regard, so that we don't end up with strange edge cases.
>

### CODE REVIEW

**Comment by Soreine** [comment]
@ianstormtaylor

The benchmark `normalize-document-twice` does a first normalization from scratch, then insert some text, and normalize again, on a large document. With memoization, or previous document comparison, we should see the impact of the second normalization disappear. So ideally, both solution should have a speed-up between x1.3 (trying to take the text insertion into account) and x2 (assuming the text insertion has zero cost).

Here are the benchmarks results on my machine:

```
Benchmarks

   normalize-document-twice
     Previous Comparison:	 170 ops/sec (117 runs sampled)
     Memoization:			 163 ops/sec (119 runs sampled)
     Bare:					 130 ops/sec (111 runs sampled)
```

Both solutions are quite close regarding the benchmarks. When testing the examples, I have not noticed any difference.

From an engineering point of view, the memoization is more generic and makes less assumptions. It also accounts for a change in the Schema. But it always loop through all the nodes. Whereas the comparison with the previous document can completely skip some nodes and their descendant. But it can break if the Schema changed (and maybe other edge cases like that).

**Comment by ianstormtaylor** [comment]
@Soreine awesome, thank you so much for doing this! A couple questions for you:

1. That's cool that they are similar in size. You mentioned still being concerned about the memoization technique looping over all of the nodes: should we double/triple the number of nodes in that document, or make them more nested, so that we can see if the two methods start to diverge?

2. I **think** there should be a way for us to make the memoization method also only have to iterate the top-most nodes, if the validation is recursive and memoized. Since that way if a top-level node hasn't changed, it will return valid immediately when compared against the same schema, so it won't have to traverse the children at all?

**Comment by Soreine** [comment]
1. I made it bigger and deeper (4*4*4*3 nodes). The results are close once again. I don't think that depth is a real-world factor. 

2. Currently, the normalization logic is bottom-up. So I wonder how :) 

What do you think if we go for the memoization path ?

**Comment by ianstormtaylor** [comment]
Nice, that sounds good! I'd like to go for the memoization path since it keeps it simpler, and it sounds like we can opportunistically make the logic faster later by having validate be top-down! Thank you!!

**Pull request merged**
