### PR TITLE
Pass down value

### PR DESCRIPTION
**Pull request by Zhouzi**
This PR fixes https://github.com/ianstormtaylor/slate/issues/1798

While going through the code I found a few things that I am concerned with:

* [ ] `value` is stored in two different places (served from the props and stored in the editor's state). It leads to bugs such as the one this PR fixes. It'd be better to have a single source of truth (for example, it's unclear when one should be used over the other, I'll have to dig deeper).
* [ ] there are lots of `render<Editor|Node>` floating around, adding several levels of indirection and making it hard to have a clear understanding of how things are rendered and with what props (for example, finding how the Schema's `renderNode` is called is not trivial).
* [ ] passing down the whole `editor` component reference seems risky. Instead, we could pass down the editor props as a `editor` prop and add the editor's relevant methods (e.g `onChange`).

### CODE REVIEW

**Comment by Soreine** [comment]
I don't think `value` is served from the props (in our app, we added it manually to all our renderNodes, to facilitate the slate upgrade)

Some preliminary research should be made about why we started passing only `editor` and not `value`. We would not want to repeat history :)
@ianstormtaylor may be insightful

**Comment by ianstormtaylor** [comment]
Originally we were passing `value` down as props, but because of `shouldComponentUpdate` there were situations where the `value` was not the latest value. So I just switched to passing down `editor` instead which will always result in `editor.value` being "latest".

Looks like I missed one place in `after.js` where `value={value}` is still being passed.

**Comment by Zhouzi** [comment]
> I don't think value is served from the props

No, it's not and that's part of the issue ^^

> Some preliminary research should be made about why we started passing only editor and not value.

[Ian suggested to pass down `value`](https://github.com/ianstormtaylor/slate/issues/1798#issuecomment-385000821) so I assume it's not too much of an issue. But perhaps I'll go for another solution where instead of passing down value as a separate prop, I'll replace the `editor` component reference by an object with the correct `value`. That way it doesn't introduce any breaking change while making it more reliable.

Anyway, I'll make sure to do the preliminary work before I make a decision 😉

**Comment by Zhouzi** [comment]
Following up on Ian's [comment](https://github.com/ianstormtaylor/slate/issues/1798#issuecomment-385000821) it seems that I missed something while testing around and passing down the value as we're used to should work. This PR may be useless, I'll give that simpler solution another try and close this PR if it becomes irrelevant 👍

**Pull request closed without merging**
